### ISSUE TITLE
[Setting] 기본설정 추가

### ISSUE THREAD

**Issue by dlrjs2360** [Techit-Springles/Backend#12]
## 📝 개요
- 팀원들의 컨트롤러 반환 형식을 맞추기 위한 기본 설정 추가

## ✅ TO-DO
- [x] Swagger 기본 설정
- [x] ResponseCode 생성
- [x] 반환 형식 ResResult 생성
- [ ] 에러 핸들러 생성
- [ ] CustomException 생성

## 📌 ETC
-
