### ISSUE TITLE
[Feature] 채팅 UI

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#127]
## 📝 개요
- 채팅방 생성 Form
- submit prevent
- 채팅방 UI 

## ✅ TO-DO
- [x] 채팅방 생성 form UI
- [x] 채팅방 생성 submit prevent
- [x] 채팅방(게임) UI

## 📌 ETC
-
