### ISSUE TITLE
[Feature] 네비게이션 UI

### ISSUE THREAD

**Issue by walwaljj** [Techit-Springles/Backend#157]
## 📝 개요
- 상태에 따른 네비게이션 보여주기

## ✅ TO-DO
- [x] 로그인 , 비 로그인 nav 구분
- [x] 게임 중, 대기 중 nav 구분
- [x] nav 에 공유하기 추가

## 📌 ETC
-
