### ISSUE TITLE
[Feature] 밤 투표 로직 짜기

### ISSUE THREAD

**Issue by ranunclulus** [Techit-Springles/Backend#166]
## 📝 개요
- 밤에 투표가 이루어지고 처리되는 로직 마무리

## ✅ TO-DO
- [x] 마피아의 투표로 사람 죽이기
- [x] 의사의 치료로 살리기
- [x] 경찰의 조사
- [x] 낮 게임 로직 sub point 조정

## 📌 ETC
-
