### ISSUE TITLE
[Feature] 게임 참여자 목록 실시간 조회 기능 개발

### ISSUE THREAD

**Issue by dlrjs2360** [Techit-Springles/Backend#176]
## 📝 개요
- 게임 참여자가 실시간으로 들어오고 나갈 수 있는 채팅방의 특성을 고려해 실시간 참여자 목록 조회 기능을 개발합니다.

## ✅ TO-DO
- [ ] 게임 참여자 목록 Topic 추가
- [ ] 참여자가 바뀔 때마다 게임 참여자들에게 목록을 새롭게 전달하는 기능 개발
- [ ] 프론트와 채팅 참여자 컨트롤러를 연결

## 📌 ETC
-
