### ISSUE TITLE
[Feature] 프론트 - 투표 연결

### ISSUE THREAD

**Issue by dlrjs2360** [Techit-Springles/Backend#178]
## 📝 개요
- 투표기능을 연동합니다.

## ✅ TO-DO
- [ ] 투표 버튼 생성 기능 개발
- [ ] 투표 정보 취합 기능 개발 및 메시지 출력
- [ ] 투표 결과 테스트
- [ ] 투표 결과 게임 종료 테스트

## 📌 ETC
-
