### ISSUE TITLE
[Feature] 투표 연결하기

### ISSUE THREAD

**Issue by ranunclulus** [Techit-Springles/Backend#206]
## 📝 개요
- 투표 시작이 잘 진행되는지 확인

## ✅ TO-DO
- [ ] 투표를 위해 임의의 player 데이터 만드는 테스트 sql 작성
- [ ] 투표 시작을 위해 임의의 투표 시작 버튼 생성 -> 나중에는 일정 시간이 지나면 투표가 진행되거나 할 것임
- [ ] console.log를 통해 빈 투표 객체가 잘 진행되는지, 어떤 메시지가 주고받아지는지 확인

## 📌 ETC
-
