### ISSUE TITLE
[Feature] 투표 확정 버튼 누르고 사람 죽이는 것까지 완료하기

### ISSUE THREAD

**Issue by ranunclulus** [Techit-Springles/Backend#225]
## 📝 개요
- 

## ✅ TO-DO
- [x] 투표 확정 버튼 누르면 해당 투표자에 대한 투표 시작
- [x] 이 사이에 타이머로 60초 변론 줄 수 있다면 주기
- [x] 투표 결과 집계해서 DayElimination 과정 진행
- [x] 제거된 정보에 따라 gameSession의 인원 재정비
- [x] nightVote 생성

## 📌 ETC
-
