### ISSUE TITLE
[Feature] nightVote 구현

### ISSUE THREAD

**Issue by ranunclulus** [Techit-Springles/Backend#236]
## 📝 개요
- nightVote 기능을 구현합시다

## ✅ TO-DO
- [x] front에 밤 투표를 진행할 투표창 띄우기
- [x] 밤 투표를 진행해서 redis에 저장하기
- [x] 결과를 집계하기
- [x] 마피아가 선택한 사람 죽이기
- [x] 의사로 방어하기
- [x] 경찰에게 조사 결과 전달
- [x] 전체에게 마피아와 의사로 인한 사상자가 있는지 전달

## 📌 ETC
-
