### ISSUE TITLE
[Feature] gameEnd 구현

### ISSUE THREAD

**Issue by ranunclulus** [Techit-Springles/Backend#237]
## 📝 개요
- 일정 조건에 따라 게임이 종료되는지 확인하고 검사

## ✅ TO-DO
- [ ] dayElimination이 끝나고 게임 종료 조건이 되었는지 검사
- [ ] nightVote가 끝나고 게임 종료 조건이 되었는지 검사
- [ ] 해당된다면 게임 세션을 종료시키기

## 📌 ETC
-
