### ISSUE TITLE
[Refactor] 채팅방 입장 api 연결

### ISSUE THREAD

**Issue by walwaljj** [Techit-Springles/Backend#247]
## 📝 개요
- 채팅방 입장 api 연결

## ✅ TO-DO
- [x] 채팅방 입장 api 연결
- [x] 빠른입장 api 연결
- [x] 빠른입장가능한 방 없을 때 메시지를 confim 으로 연결하기 

## 📌 ETC
-
