### ISSUE TITLE
[Feature] 채팅창 디자인 수정

### ISSUE THREAD

**Issue by dlrjs2360** [Techit-Springles/Backend#260]
## 📝 개요
- 채팅창에서 나와 상대방의 채팅을 구분하고 관리자의 채팅을 강조합니다.

## ✅ TO-DO
- [ ] 내 채팅 오른쪽 정렬
- [ ] 상대방 채팅 왼쪽 정렬
- [ ] 관리자 채팅 강조

## 📌 ETC
-
