### ISSUE TITLE
[Feature] 채팅 참여자 디자인 수정 

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#270]
## 📝 개요
- 채팅 참여자 목록에서 참여자의 레벨, 닉네임을 함께 보여줍니다. 

## ✅ TO-DO
- [x] 리스트 점 없애기
- [x] 참여자 프로필 사진 함께 보여주기
- [ ] 참여자 레벨 사진 함께 보여주기
- [x] 참여자 이름 대신 닉네임으로 변경

## 📌 ETC
-
