### ISSUE TITLE
[Feature] 종료 조건 검색 후 사상자 발생했을 때 게임 종료

### ISSUE THREAD

**Issue by ranunclulus** [Techit-Springles/Backend#293]
## 📝 개요
- 사상자가 발생할 때마다 종료가 되었는지 검사

## ✅ TO-DO
- [ ] 종료 조건 검사
- [ ] 게임 결과 기록
- [ ] 게임 기록 출력
- [ ] 다시 게임 시작 전 원래 채팅방 상태로 변경

## 📌 ETC
-
