### ISSUE TITLE
[Feature] 채팅방 입/퇴장 시 참여 인원 변경

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#296]
## 📝 개요
- 채팅방 입장/퇴장 시 head(참여 인원)이 바뀌지 않는 문제 발생해서 api 추가와 js 코드 수정 

## ✅ TO-DO
- [x] 채팅방 입장 api 수정
- [x] 채팅방 퇴장 api 생성
- [x] index.html 에서 채팅방 입장할 때 js 코드 수정(location.href 대신 채팅방 입장 ajax로 수정)
- [x] chat-room.html에서 채팅방 퇴장 시 js 코드 수정 (location.href 대신 채팅방 입장 ajax로 수정)

## 📌 ETC
-
