### ISSUE TITLE
[Setting] 프로젝트 세팅 변경

### ISSUE THREAD

**Issue by dlrjs2360** [Techit-Springles/Backend#3]
## 📝 개요
- gitignore와 yml파일 등 기본적인 환경 설정

## ✅ TO-DO
- [x] gitignore 수정
- [x] 개발,배포,기본 버전 yml 추가
- [x] 기존 엔티티 매핑구조 실행 확인
- [x] 필요한 의존성 추가

## 📌 ETC
-
