### ISSUE TITLE
[Feature] 채팅방 정원 초과 또는 게임 중인 경우 입장 불가

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#336]
## 📝 개요
- 채팅방 정원을 초과하거나 게임 진행 중인 경우 입장 할 수 없도록 block 합니다.

## ✅ TO-DO
- [ ] 정원 초과 시 Exception 코드 추가 
- [ ] 게임 중인 경우 Exception 코드 추가 
- [ ] 화면에서 정원 초과시 or 게임중인 경우 클릭하지 못하도록 막기 

## 📌 ETC
-
