### ISSUE TITLE
[Feature] 채팅방 수정

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#43]
## 📝 개요
- 생성된 채팅방을 수정

## ✅ TO-DO
- [x] 채팅방 권한은 방장에게만 있다.
- [x]  수정 시 validation 적용
- [x] 수정 static method 작성

## 📌 ETC
-
