### ISSUE TITLE
[Feature] 채팅방 삭제 API

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#54]
## 📝 개요
- 채팅방 삭제 API

## ✅ TO-DO
- [x]  방장이 방을 떠나면 채팅방 자동 삭제
- [x] 기존에 했던 채팅 로그들 같이 삭제
- [x] 나가면 채팅 목록 페이지로 이동 

## 📌 ETC
-
