### ISSUE TITLE
[Feature] 채팅룸 페이지 화면

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#57]
## 📝 개요
- 채팅룸 페이지 화면(메인페이지)을 타임리프로 생성

## ✅ TO-DO
- [x] thymeleaf dependency 추가
- [x] templates/home 페이지 생성
- [x] navigation
- [x] 유저 표시(image, link)
- [x] 게임 만들기(button)
- [x] 빠른 입장 (button)
- [x] 방 검색 (input)
- [x] 방 목록 (pagination)

## 📌 ETC
-
