### ISSUE TITLE
[Feature] 채팅룸 url 연결

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#83]
## 📝 개요
- 채팅룸 생성 페이지, 생성 로직, 목록 페이지, 목록 조회가 가능하게 합니다.
- 채팅룸 목록 item을 클릭 시 localhost/8080/chat/{roomId}/{name}으로 이동합니다.

## ✅ TO-DO
- [x] 채팅룸 생성 페이지
- [x] 채팅룸 생성
- [x] 채팅룸 목록 페이지
- [x] 채팅룸 목록 조회 
- [x] 채팅룸 클릭 시 url로 이동해 채팅과 연결 

## 📌 ETC
-
