### ISSUE TITLE
[Feature] Token 저장과 클라이언트 RequestHeader 설정

### ISSUE THREAD

**Issue by ujumom** [Techit-Springles/Backend#91]
## 📝 개요
Client에서 사용자 정보가 필요하거나, API 요청시 RequestHeader의 Authentication에 AccessToken을 추가해야 합니다.
Cookie에 저장된 토큰을 Header에 넣어주는 클라이언트 전역 함수를 생성하고자 합니다. 

## ✅ TO-DO
- [x] accessToken을 🍪HttpOnly Cookie에 저장
- [x] refreshToken id(index 값) 🍪HttpOnly Cookie에 저장
- [ ]  ajax로 Cookie에 담긴 AccessToken을 Header에 넣는 함수 개발
- [x] 사용자 정보 요청 API
- [x] 사용자 정보 dto 

## 📌 ETC
-
